DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webdoc/EN/graphics

NONEXEC_TARGETS += criteria.gif
NONEXEC_TARGETS += get_one_array_order.gif
NONEXEC_TARGETS += schema_analysis.jpg
NONEXEC_TARGETS += schema_layout.jpg
NONEXEC_TARGETS += schema_main.jpg
NONEXEC_TARGETS += schema_order_billing.jpg
NONEXEC_TARGETS += schema_security.jpg
NONEXEC_TARGETS += quality_control.gif
NONEXEC_TARGETS += quality_control_plot.gif
NONEXEC_TARGETS += quality_control_text.gif
NONEXEC_TARGETS += differential_discovery.gif
NONEXEC_TARGETS += differential_discovery_out.gif
NONEXEC_TARGETS += filter1.gif
NONEXEC_TARGETS += filter2.gif
NONEXEC_TARGETS += filter_out.gif
NONEXEC_TARGETS += cluster.gif
NONEXEC_TARGETS += cluster_out.gif
NONEXEC_TARGETS += ncbi.gif
NONEXEC_TARGETS += multicond.gif
 
include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk
