DEPTH = ../../..
DEST_DIR = $(LIB_DIR)/GEOSS/Arraycenter

NONEXEC_TARGETS += Order.pm Organization.pm

BUILD_TARGETS += test-lib.cgi
TEST_LIBS = $(NONEXEC_TARGETS)

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk
