DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webdoc/EN/examples

NONEXEC_TARGETS += B6_ameba_1.EXP
NONEXEC_TARGETS += B6_ameba_1.RPT
NONEXEC_TARGETS += affymetrix_txt.txt
NONEXEC_TARGETS += arraymeasurement.txt
NONEXEC_TARGETS += chip_name.txt
NONEXEC_TARGETS += disease.txt
NONEXEC_TARGETS += exp_condition.txt
NONEXEC_TARGETS += order_info.txt
NONEXEC_TARGETS += sample.txt
NONEXEC_TARGETS += single_data_file.txt
NONEXEC_TARGETS += study.txt
 
include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk
