DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/addLinks
BUILD_TARGETS = addLinks_1.cgi
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS = addLinks_1.html addLinks_1.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

