DEPTH = ../../..
DEST_DIR = $(LIB_DIR)/GEOSS/User

NONEXEC_TARGETS += User.pm Group.pm

BUILD_TARGETS += test-lib.cgi
TEST_LIBS = $(NONEXEC_TARGETS)

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk
