DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/diffDiscMult
BUILD_TARGETS = 
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS += diffDiscMult_2.html
NONEXEC_TARGETS += diffDiscMult_2.rw
NONEXEC_TARGETS += diffDiscMult_2.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

