DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/diffDiscover
BUILD_TARGETS = 
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS += diffDiscover_4.cfg
NONEXEC_TARGETS += diffDiscover_4.rw
NONEXEC_TARGETS += diffDiscover_4.html

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

