DEPTH = ../../..
DEST_DIR = $(WEB_DIR)/site/webdoc/EN
SUBDIRS = graphics html examples
BUILD_TARGETS = doc-html-done

XML_SOURCE += admin_command.xml
XML_SOURCE += admin_faq.xml
XML_SOURCE += admin_gui.xml
XML_SOURCE += admin_guide.xml
XML_SOURCE += admin_workflow.xml
XML_SOURCE += array_center_staff_faq.xml
XML_SOURCE += array_center_staff_gui.xml
XML_SOURCE += array_center_staff_guide.xml
XML_SOURCE += array_center_staff_workflow.xml
XML_SOURCE += data_load_faq.xml
XML_SOURCE += data_load_guide.xml
XML_SOURCE += developer_article_documentation.xml
XML_SOURCE += developer_faq.xml
XML_SOURCE += developer_guide.xml
XML_SOURCE += glossary.xml
XML_SOURCE += index.xml
XML_SOURCE += install.xml
XML_SOURCE += install_faq.xml
XML_SOURCE += overview.xml
XML_SOURCE += special_center_faq.xml
XML_SOURCE += special_center_gui.xml
XML_SOURCE += special_center_guide.xml
XML_SOURCE += special_center_workflow.xml
XML_SOURCE += summary.xml
XML_SOURCE += user_article_analysis_tutorial.xml
XML_SOURCE += user_faq.xml
XML_SOURCE += user_gui.xml
XML_SOURCE += user_guide.xml
XML_SOURCE += user_workflow.xml

SPELLCHECK = $(XML_SOURCE)

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk
