DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/filterMult
BUILD_TARGETS = 
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS += filterMult_2.html filterMult_2.rw filterMult_2.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

