DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/permCluster
BUILD_TARGETS = 
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS = permCluster_1.html permCluster_1.rw permCluster_1.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

