DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/classification
NONEXEC_TARGETS += classification_2.html
NONEXEC_TARGETS += classification_2.rw
NONEXEC_TARGETS += classification_2.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk
