DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/westfallYoung
BUILD_TARGETS = 
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS = westfallYoung_1.html westfallYoung_1.rw westfallYoung_1.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

