DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/affy
BUILD_TARGETS = 
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS = affy_1.html affy_1.rw affy_1.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

