DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/filter
BUILD_TARGETS = 
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS += filter_4.html
NONEXEC_TARGETS += filter_4.rw
NONEXEC_TARGETS += filter_4.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

