DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/treedraw
BUILD_TARGETS = treedraw_1.cgi
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS = treedraw_1.html treedraw_1.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

