DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/cluster
BUILD_TARGETS = cluster_3.cgi
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS += cluster_3.html
NONEXEC_TARGETS += cluster_3.cfg
NONEXEC_TARGETS += cluster_3.rw

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

