DEPTH = ../..
DEST_DIR = $(WEB_DIR)/site/public_data
BUILD_TARGETS = index.cgi
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS += index.html indexnone.html 

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

