DEPTH = ../../../..
DEST_DIR = $(WEB_DIR)/site/webtools/analysis/qualityControl
BUILD_TARGETS = 
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS = qualityControl_3.html qualityControl_3.rw qualityControl_3.cfg

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = 

