DEPTH = ../..
DEST_DIR = $(WEB_DIR)/site/webdoc
BUILD_TARGETS =  
EXEC_TARGETS = $(BUILD_TARGETS)
NONEXEC_TARGETS = 

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk

$(BUILD_TARGETS): $(DEPTH)/perl-header

SUBDIRS = EN

