DEPTH = ../..
DEST_DIR = $(WEB_DIR)/site/curtools


BUILD_TARGETS += assign_order_number.cgi
BUILD_TARGETS +=choose_order_curator.cgi
BUILD_TARGETS +=delete_order.cgi
BUILD_TARGETS +=edit_order_curator2.cgi
BUILD_TARGETS +=index.cgi
BUILD_TARGETS +=insert_order_curator1.cgi
BUILD_TARGETS +=insert_order_curator2.cgi
BUILD_TARGETS +=insert_order_curator3.cgi
BUILD_TARGETS +=link_order_number.cgi
BUILD_TARGETS +=load_data1.cgi
BUILD_TARGETS +=load_data2.cgi
BUILD_TARGETS +=show1_curator.cgi
BUILD_TARGETS +=show_study_curator.cgi
BUILD_TARGETS +=view_account.cgi
BUILD_TARGETS +=view_reports1.cgi
BUILD_TARGETS +=view_brief_curator.cgi
BUILD_TARGETS +=view_reports2.cgi
BUILD_TARGETS +=view_reports.cgi
BUILD_TARGETS +=view_qc_curator.cgi

EXEC_TARGETS = $(BUILD_TARGETS)

NONEXEC_TARGETS += assign_order_number.html
NONEXEC_TARGETS +=choose_order_curator.html
NONEXEC_TARGETS +=delete_order.html
NONEXEC_TARGETS +=index.html
NONEXEC_TARGETS +=insert_order_curator1.html
NONEXEC_TARGETS +=insert_order_curator2.html
NONEXEC_TARGETS +=link_order_number.html
NONEXEC_TARGETS +=load_data1.html
NONEXEC_TARGETS +=load_data2.html
NONEXEC_TARGETS +=show1_curator.html
NONEXEC_TARGETS +=show_study_curator.html
NONEXEC_TARGETS +=view_account.html
NONEXEC_TARGETS +=view_brief_curator.html
NONEXEC_TARGETS +=view_reports.html
NONEXEC_TARGETS +=view_reports1.html
NONEXEC_TARGETS +=view_qc_curator.html
NONEXEC_TARGETS +=order_created_email.txt
NONEXEC_TARGETS +=pi_email.txt
NONEXEC_TARGETS +=order_loaded_email.txt

include $(DEPTH)/build-options.mk
include $(DEPTH)/subdirs.mk
include $(DEPTH)/rules.mk


$(BUILD_TARGETS): $(DEPTH)/perl-header


